name: Bug Report
description: Create a report to help us improve OCX
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: input
    id: version
    attributes:
      label: OCX Version
      description: What version of OCX are you running? (Run `ocx --version`)
      placeholder: 0.1.0-alpha.1
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running? (e.g. Ubuntu 22.04, macOS Sonoma)
    validations:
      required: true

  - type: input
    id: docker
    attributes:
      label: Docker Version
      description: Output of `docker --version`
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'ocx opencode'
        2. Execute '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Output
      description: If applicable, add error logs or output.
      render: shell
